name: Update Latest Blog
on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hour
    - cron: "0 */2 * * *"
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: armingli/readme-update-actions@v1.1.1
        with:
          max_post: 5
          rss_list: "https://blog.metaprogramming.space/rss.xml"
      - name: Commit and push
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "action@github.com"
          git add .
          git commit -m "profile updated" || true
          git push origin main
